import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppNavbar from "./components/Navbar";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className="flex h-screen flex-col bg-[#0B0D17] text-gray-100">
            <header className="flex justify-between items-center border-b border-gray-800/50 bg-[#0B0D17]/95 backdrop-blur-sm px-6 py-3">
              <div className="flex items-center space-x-8">
                <h1 className="text-xl font-bold text-gray-100 tracking-tight">StudyBuddy</h1>
                <AppNavbar />
              </div>
              <div className="flex items-center gap-3">
                <SignedOut>
                  <SignInButton className="text-gray-400 hover:text-gray-100 border border-gray-700 hover:border-gray-600 py-2 px-4 rounded-lg transition-all duration-200 text-sm" />
                  <SignUpButton className="bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 rounded-lg transition-all duration-200 text-sm font-medium" />
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </header>
            <main className="flex-1 overflow-y-auto">
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}